{% set version = "0.1" %}


package:
  name: _libgcc_mutex
  version: {{ version }}

{% for build_string in ("main", "free") %}
build:
  string: {{ build_string }}
{% endfor %}

about:
  summary: Mutex for libgcc and libgcc-ng 
